#!/usr/bin/python3
'''
convert srt to ass with a suitable format
'''

import argparse
from threading import Thread

import pysubs2

BORDER = 'ScaledBorderAndShadow'

FONT = 'DejaVu Sans'
FONT_SIZE = 20
MARGINV = 2

EN_STYLE = r'{\fs14}'


def main(srt_in):
    subs = pysubs2.load(srt_in, encoding='UTF-8')

    subs.info[BORDER] = 'no'

    subs.styles['Default'].fontname = FONT
    subs.styles['Default'].fontsize = FONT_SIZE
    subs.styles['Default'].marginv = MARGINV

    for sub in subs:
        position = sub.text.find(r'\N')
        if position != -1:
            sub.text = sub.text[:position] \
                + r'\N' + EN_STYLE\
                + sub.text[position + 2:]

    subs.save(srt_in[:-4] + '.ass', encoding='UTF-8')


if __name__ == '__main__':
    PARSER = argparse.ArgumentParser(
        description='convert srt format to ass with a suitable style.'
    )
    PARSER.add_argument(
        'srt_input',
        nargs='+',
        help='input subtitles file(s)',
    )
    ARGS = PARSER.parse_args()

    for arg in ARGS.srt_input:
        Thread(target=main, args=[arg]).start()
